---
#ansible-playbook create_bob_playbook.yml --vault-id prod
- name: Add bob
  hosts: all
  become: true
  tasks:
    - name: debug 
      ansible.builtin.debug:
        msg: bob password {{ bob_password }}

    - name: Add bob
      ansible.builtin.user:
        name: "bob"
        state: present
        groups: "sudo"
        password: "{{ bob_password | password_hash('sha512') }}"
